apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrust-backend-jwt-secret
  namespace: storefront-dev777
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: t5-dev/storefront-dev777/JWT_SECRET
